name: Build Project

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Устанавливаем необходимые зависимости для Ubuntu
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential pkg-config libusb-1.0-0-dev

    # Запускаем сборку
    - name: Run Build
      run: |
        make

    # Сохраняем результат
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-compiled-program
        path: .
