name: Build Project

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Пытаемся собрать проект стандартным make
    - name: Run Build
      run: |
        make

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-compiled-program
        # Символ ловит все измененные или созданные файлы, 
        # чтобы мы точно не пропустили готовую программу
        path: .
